stages:
  - test
  - build
  - deploy

Unit_test:
  stage: test
  allow_failure: true
  image: node:18.16.0-alpine3.17
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - dist/

e2e_test:
  stage: test
  allow_failure: true
  image: node:18.16.0-alpine3.17
  script:
    - npm install
    - npm run test:e2e
  artifacts:
    paths:
      - dist/

cov_test:
  stage: test
  allow_failure: true
  image: node:18.16.0-alpine3.17
  script:
    - npm install
    - npm run test:cov
  artifacts:
    paths:
      - dist/

build:
  stage: build
  image: node:18.16.0-alpine3.17
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

build_and_push_image:
  stage: deploy
  image: docker:stable

  services:
    - docker:dind

  before_script:
  - docker --version
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
  script: 
    - docker build -t $CI_REGISTRY_IMAGE:all-in-one-1.0.1 .
    # - docker tag ngdrs-bcn-gateway:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:all-in-one-1.0.1
    - docker logout $CI_REGISTRY
